### ISSUE TITLE
关于Legacy BIOS - 0x13中断

### ISSUE THREAD

**Issue by Gmoonnight** [dibingfa/flash-linux0.11-talk#94]
如果我的电脑连接着一块机械硬盘，一块固态硬盘，一个U盘，一个软盘，它们分别存储着不同的操作系统，那么此时我从U盘启动操作系统的安装，它们的驱动器号分别是什么？
另外，关于bios中断有统一的标准和官方文档吗？
<img width="646" alt="image" src="https://github.com/dibingfa/flash-linux0.11-talk/assets/20857405/ee2c1c1b-c931-4720-bf77-1662a3f785bd">
<img width="1274" alt="image" src="https://github.com/dibingfa/flash-linux0.11-talk/assets/20857405/d7c4fb06-235e-451f-8a23-219bc0b3a71b">

**Comment by muyiyangyang** [comment]
你好，你的邮件已收到，谢谢！

**Comment by superjcd** [comment]
收到了，谢谢

**Comment by KunYi** [comment]
check this https://en.wikipedia.org/wiki/INT_13H
通常這個編號是按照BIOS偵測順序來的
看硬體界面的順序　不過一般順序會是
机械硬盘(0x80)，一块固态硬盘(0x81)，一个U盘(0x82)，一个软盘(0x00)

**Comment by Gmoonnight** [comment]
> check this https://en.wikipedia.org/wiki/INT_13H 通常這個編號是按照BIOS偵測順序來的 看硬體界面的順序　不過一般順序會是 机械硬盘(0x80)，一块固态硬盘(0x81)，一个U盘(0x82)，一个软盘(0x00) 不過如果你的"固态硬盘"是NVM 我猜可能你的BIOS連INT13 都沒有 這幾年的電腦只有UEFI 沒有legacy BIOS的CSM模組了

这是一台10年的电脑，既支持Legacy BIOS也支持UEFI；
<img width="786" alt="image" src="https://github.com/dibingfa/flash-linux0.11-talk/assets/20857405/4e28b01c-ac0a-4c45-ac02-4a95e4fb1b9c">

所以这个项目是基于Legacy BIOS的是吗？我理解的是这样的：
<img width="679" alt="image" src="https://github.com/dibingfa/flash-linux0.11-talk/assets/20857405/922e8d4a-c1b8-484a-9d91-7108fd0e6b3d">

其次，项目中的这张图片是软盘的编号，而第四节的表述是磁盘或硬盘拷贝到内存，在软盘已经消失的今天，会给人很大的困惑；
<img width="723" alt="image" src="https://github.com/dibingfa/flash-linux0.11-talk/assets/20857405/d9d4e072-9e01-4ae9-b6fe-e93f68e8efce">

然后，我现在的困惑在于，我可以通过第一张图片显示的那样选择我的启动设备，比如：u盘、固态硬盘、机械硬盘等，os程序在进行磁盘扇区拷贝到内存前，如何知道启动设备编号，以调用int 0x13中断服务程序？

**Comment by Gmoonnight** [comment]
<img width="1277" alt="image" src="https://github.com/dibingfa/flash-linux0.11-talk/assets/20857405/29763cf4-53a6-4ef2-b548-d42eba58cf5c">
我找了，谢谢！

**Comment by KunYi** [comment]
那個號碼是legacy BIOS自己指定的　它當然知道 你這個電腦是 UEFI with CSM module 本質是UEFI 但是他有把legacy BIOS的功能做出來

BIOS 本身提供界面　讓使用者呼叫 int13 是OS loader 或是DOS 本身操作磁碟時約定的界面，這樣OS本身不需要知道硬件是那個，它直接就能使用int 13h 去讓BIOS替它工作　你可以把BIOS看成一個寫好的函式庫　只是因為那古早的時代，它們是約定使用軟體中斷來傳遞資料 BIOS工程師針對硬件環境寫好對應的界面　讓上層軟件調用 譬如它跟上層軟件約定好 00~7F 屬於Floppy, 080h 屬於系統內第一個Hardisk , 譬如這樣好了系統上都沒有Harddisk 也沒有Floopy 但是支持U盤開機, 這時U盤就會被BIOS認為他是第一個硬盤　配給他的編號就是0x80, 如果有硬盤一個 0x80 就是實際的硬盤, 0x81 就是U盤類似這樣的都是BIOS內部算法決定的

**Comment by Gmoonnight** [comment]
好滴，感谢~
